### ISSUE TITLE
Listen Problem

### ISSUE THREAD

**Issue by apinz** [juwit-team/juwit-editor#2]
Latex meckert (nach parsen), wenn auf
```html
<ol> oder <ul> kein <li> folgt.
```

Beispiel 1:
```html
<p>ersz</p>
<ul>
  <li>srg</li>
  <ul>
    <li>tz</li>
    <ul>
      <ul>
        <li>czuc#</li>
      </ul>
    </ul>
  </ul>
  <li><br></li>
</ul>
<p><br></p>
<p></p>
<p></p>
```

Beispiel 2:
```html
<ol> </ol>
```

**Comment by repthor** [comment]
<ul><ul> wird nun beim Betätigen der "PDF"-Taste mit der Meldung "multiple unordered list found",
<ol>ol> mit der Meldung "multiple ordered list found" zurückgewiesen. Post wird nicht ausgeführt.
