### ISSUE TITLE
ordered lists

### ISSUE THREAD

**Issue by repthor** [juwit-team/juwit-editor#9]
LaTex (oder wer auch immer) liefert im PDF bei der 2. Schachtelungsstufe kleine römische Ziffern als Nummer des Elements. In der 3. Schachtelungsstufe dann kleine Buchstaben. 
Im Eingabefenster und in der Vorschau rechts werden hingegen stets (in jeder Schachtelungstiefe) arabische Ziffern zur Numerierung verwendet.

**Comment by maxxst** [comment]
sollte jetzt funktionier siehe e19ec7c62d11557847d085f0b0ab722abf50e295
